[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.0.8"
fibonacci-lib = { path = "../lib" }
substrate-bn = {git = "https://github.com/paritytech/bn", branch = "master"}
bn-with-bigint-operational = {path = "../../../crates/bn-with-bigint-operational"}
