[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.0.8"
fibonacci-lib = { path = "../lib" }
ark-ec = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-precompile-24"}
ark-ff = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-precompile-24", features = ["std"]}
ark-bn254 = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-precompile-24"}


# ark-ec = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-main-6"}
# # ark-ff = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-main-0", features = ["std"]}
# ark-ff = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-main-6", features = ["std"]}
# ark-bn254 = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-main-6"}


# ark-ec = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-6"}
# # ark-ff = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-6", features = ["std"]}
# ark-ff = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-6"}
# ark-bn254 = {git = "https://github.com/developeruche/algebra.git", branch = "sp1-patch-6"}