[workspace]
members = [
"crates/bench-utils", 
"crates/bn-with-bigint-total", 
"crates/bn-with-bigint-operational", 
"crates/bench-utils-patched"]

exclude = [
    "bin/bn-pairing",
    "bin/bn-pairing-patched",
    "bin/bigint-pairing",
]
